### ISSUE TITLE
Browser-mod breaking update breaks channel-pad and some others as well?

### ISSUE THREAD

**Issue by MEKadan** [madmicio/LG-WebOS-Remote-Control#100]
Like the title says, the new browser-mod upgrade breaks things in here, especially channel-pad and number-pad. Maybe some others as well. At least so I think, because some functionality is lost and on the other hand, readme states, the browser-mod is needed for this.

Browser-mod states  it will break everything in this new ver 2, and so it seems to be doing... How to correct?

**Comment by madmicio** [comment]
fixed

**Comment by MEKadan** [comment]
Wow! That was quick :)
