### ISSUE TITLE
Cant find card in lovelace

### ISSUE THREAD

**Issue by BorjaIkasle** [madmicio/LG-WebOS-Remote-Control#126]
I install it though hacs but it doesn´t appear in lovelace options altough I have the resources correctly. I should make something special? When I put - type: 'custom:lg-remote-control' it doesn´t load neither, restart doesn´t work neither

**Comment by tebeso** [comment]
You will not be able to find it in the overview. Instead, scroll to the bottom and add "Custom Card" or something. In the textfield, add this (dont forget to change entity and mac):

type: 'custom:lg-remote-control'
entity: media_player.tv_lg_55c8
mac: xx:xx:xx:xx

**Comment by BorjaIkasle** [comment]
> You will not be able to find it in the overview. Instead, scroll to the bottom and add "Custom Card" or something. In the textfield, add this (dont forget to change entity and mac):
> 
> type: 'custom:lg-remote-control' entity: media_player.tv_lg_55c8 mac: xx:xx:xx:xx

I already did that but nothing

**Comment by kumarvbharath** [comment]
I am getting the same error too. i downloaded from HACS and loaded it, and the resources were added automatically. but when i try to add a manual card, i do see similar error. pasting an image of it.

<img width="733" alt="image" src="https://github.com/madmicio/LG-WebOS-Remote-Control/assets/64459834/64e74578-5dd7-4fc3-b9e5-5be17741925e">

**Comment by mgartin** [comment]
I've had this installed for some time, but after an update it stopped working, I now have this:
![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/25937034/3232ed57-a48b-4a82-8535-ebb5f6887a26)

It might have happened after updating HACS to 1.33.0.
HA runs with these versions:
Home Assistant 2023.10.5 
Supervisor 2023.10.0 
Operating System 11.0
Frontend 20231005.0 - latest

**Comment by MikeDeltaHH** [comment]
Have the same problem and still used the cards to switch my LG TVs over the weekend - I think the problem came with the HAOS 10.5 core update, but not sure....

![Screenshot 2023-10-24 192916](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/34737987/44e36e54-8e78-4e32-8ac5-f7255c19aa4b)

Home Assistant 2023.10.5
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

**Comment by madmicio** [comment]
I'm also on 2023.10.5 and I don't have any problems.  however I'm working on a new version that has the graphical configuration.

**Comment by Turton** [comment]
Same issue.  Weirdly it works with Edge, not Chrome and not on Android.

**Comment by MikeDeltaHH** [comment]
> I'm also on 2023.10.5 and I don't have any problems. however I'm working on a new version that has the graphical configuration.

What do you mean by that? I use the latest version via HACS...

**Comment by Turton** [comment]
Although the main remote seems to still display and function in Edge, the channel card fails in the same way.
![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/12547793/67ecba0d-77ee-451f-8d59-46a41ed5f3c5)

**Comment by MikeDeltaHH** [comment]
I hope madmicio can solve the problem, I have not found a card with the same function...

**Comment by MikeDeltaHH** [comment]
> I'm also on 2023.10.5 and I don't have any problems. however I'm working on a new version that has the graphical configuration.

Great, thanks for info!

**Comment by Turton** [comment]
@MikeDeltaHH, I managed to resolve this by selecting 'Redownload' from HACS.  Beforehand, Edge had also stopped working, after a 'Redownload' and browser refresh it came back to life.  I repeated this on Android, (not sure I need to do it twice), but it did the trick.  All functioning again across all platforms.

**Comment by MikeDeltaHH** [comment]
> @MikeDeltaHH, I managed to resolve this by selecting 'Redownload' from HACS. Beforehand, Edge had also stopped working, after a 'Redownload' and browser refresh it came back to life. I repeated this on Android, (not sure I need to do it twice), but it did the trick. All functioning again across all platforms.

Thanks a lot - this helps and solved the issue for me too!

**Comment by LukaszP2** [comment]
I upgrade to 2.0 and card doesn't exist:
![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/44735995/656cd3fc-da69-4647-9e4b-2ead99c86718)
Core: 2023.11.2
Supervisor: 2023.11.3

**Comment by Clam58** [comment]
Same issue as @LukaszP2 

Home Assistant
Core
2023.11.2
Supervisor
2023.11.0
Operating System
11.1
Frontend
20231030.2

Tried redownloading as recommended earlier but made no difference

**Comment by Clam58** [comment]
The resource string seems to be missing information. I manually edited it from

hacsfiles/LG-WebOS-Remote-Control/null?hacstag=[25700599020](tel:25700599020)

to

hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=[25700599020](tel:25700599020)

and the loading error cleared

**Comment by richsimpson** [comment]
Yes updating resource for me has worked. Wasn't sure what that meant initially so incase there is anyone even less competent, here is what to do!

SETTINGS
DASHBOARDS
click the top right icon for menu
select 'RESOURCES'
then locate the entry that says:
hacsfiles/LG-WebOS-Remote-Control/null?hacstag=25700599020

and update it to

hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=25700599020

select 'UPDATE'
check remote now shows, if not refresh page.

Though I do now have a message in HACS to tell me something isn't loaded correctly. Presume it is this?

![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/51749826/061d7109-f3f8-4920-b659-7cbe555b7d6e)

**Comment by Clam58** [comment]
![IMG_0107](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/79151293/3542e7f5-2b3a-42a0-af4d-a0c9b97a338f)

But the card is working in HA

**Comment by KameDomotics** [comment]
> Yes updating resource for me has worked. Wasn't sure what that meant initially so incase there is anyone even less competent, here is what to do!
> 
> SETTINGS DASHBOARDS click the top right icon for menu select 'RESOURCES' then locate the entry that says: hacsfiles/LG-WebOS-Remote-Control/null?hacstag=25700599020
> 
> and update it to
> 
> hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=25700599020
> 
> select 'UPDATE' check remote now shows, if not refresh page.
> 
> Though I do now have a message in HACS to tell me something isn't loaded correctly. Presume it is this?
> 
> ![image](https://user-images.githubusercontent.com/51749826/282896951-061d7109-f3f8-4920-b659-7cbe555b7d6e.png)

I have the same error in Hacs, but now the card working

**Comment by mattdevo1** [comment]
I have the same issue. Upgraded to 2.0.1 and this started. Rolled back to 1.1.3 and it's fixed.

Running HA 2023.11.2.
