### ISSUE TITLE
Issue loading from HACS

### ISSUE THREAD

**Issue by briadelour** [madmicio/LG-WebOS-Remote-Control#135]
First off this integration is great!  The remote works great, but I have one issue I can't figure out.

When I initially load from HACS the card gives an error that states: "Custom element doesn't exist: lg-remote-control."

So I go back and check my lovelace resources and this is what is registered for the URL: "/hacsfiles/LG-WebOS-Remote-Control/**null**?hacstag=257005990201"

The "null" doesn't look right, so I check the file location and see that the relative path is /config/www/community/LG-WebOS-Remote-Control/lg-remote-control.js

So I got back to my lovelace resources and change the path to: replace "null" with "lg-remote-control.js" so the full path is: /hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=257005990201

Then I go back to my browser with lovelace, refresh and the remote works again.  But if I go to /hacs/frontend the frontend integration displays in a red box with "Not loaded" at the top, but I know it's loaded because it works fine.  
![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/117751504/451d256b-67fe-4758-8ec4-85dd0230264e)

Additionally, each time I go to /hacs/entry I see a warning message, but again, I know everything is working properly: 
![image](https://github.com/madmicio/LG-WebOS-Remote-Control/assets/117751504/84a0e792-ca34-4067-9b47-476565910086)

I've gone through a search of resources and I can't find a double entry pointing to the same .js file.

**Comment by madmicio** [comment]
fixed

**Comment by briadelour** [comment]
Confirmed!  Thanks for the quick turnaround!
