### ISSUE TITLE
Channels not working

### ISSUE THREAD

**Issue by elishaip** [madmicio/LG-WebOS-Remote-Control#155]
After I click on the icon /local/pics/babyisrael.png
There is no response and there is an error message. See attached screenshots.

How can it be solved?

Thanks.

![2024-09-19_015201](https://github.com/user-attachments/assets/a6e7f169-a5fa-4884-9cb4-3d8dc90017ec)
![2024-09-19_015628](https://github.com/user-attachments/assets/c2f568c9-fa4b-4fef-8e63-cd091e2f7b5a)
![2024-09-19_015634](https://github.com/user-attachments/assets/3ef73c5a-be2a-4ee9-8fef-1bc1e4867ec7)

**Comment by danibauti94** [comment]
The same thing happens to me after updating to iOS 18. With iOS 17 I had no problems.

**Comment by madmicio** [comment]
it's reported in the readme as an example!
 you have to write '1' not /1
