### ISSUE TITLE
Channel request

### ISSUE THREAD

**Issue by SeLLeRoNe** [madmicio/LG-WebOS-Remote-Control#22]
Hi there,
Would be possible to have the list of channels as showed in this screen?
https://raw.githubusercontent.com/madmicio/LG-WebOS-Remote-Control/master/example/channels.jpg

Thanks :)

**Comment by madmicio** [comment]
I don't understand, do you want those channels shown in photos, ready in yaml format to be inserted in lovelace?

**Comment by SeLLeRoNe** [comment]
If possible yes please.
I am trying to implment this for my father (unfortunately I have not an LG TV :) )

Since he lives in Italy would be much easier if you can share that code without having to re-create it.

Thanks

PS. If not possible, thanks anyway :)

**Comment by SeLLeRoNe** [comment]
Not possible?

**Comment by madmicio** [comment]
https://pastebin.com/QbhkqZXp

**Comment by SeLLeRoNe** [comment]
Thanks! :)
