### ISSUE TITLE
Feature request: Hide / show buttons

### ISSUE THREAD

**Issue by eyalcha** [madmicio/LG-WebOS-Remote-Control#25]
In addition to scaling, it will be nice to have the option to control which buttons will be shown / hide.
The reason is that to have all buttons on one mobile screen, scaling make all buttons small, while on the other hand, not all buttons are being used.

Adding the option to control which buttons will be shown or hide can reduce the scaling factor which will make buttons in reasonable size on mobile devices.

It is also oj if you can start with group of buttons, e.g., all the play / stop /pause buttons (in the bottom of the remote)

**Comment by lucifudge** [comment]
Please add this! I have no use for certain buttons (example: I don't need channel pad or key pad because I don't use the TV tuner - I use a cable box over HDMI which uses a different remote).

**Comment by kongo09** [comment]
+1

**Comment by madmicio** [comment]
for this project no developments are currently foreseen.
your requests are really interesting, but
as it is not a commercial product at the moment I cannot invest further resources on it
