### ISSUE TITLE
hi how can this be setup

### ISSUE THREAD

**Issue by Drwarfare** [madmicio/LG-WebOS-Remote-Control#35]
in the instructions it says to install using HACS but when i go to HACS it doesnt appear also do i need to add it as a new repository.

is the browser_mod required and channel-pad required and do i have to use a repository for them if they do can you add to comment a link for that so i can add it to my HACS

many thanks

ghost

**Comment by madmicio** [comment]
Hacs => fronyend
Search: lg

**Comment by nirt00** [comment]
hi, i install it but i trying to add it and to see the remote with no success.
what am i missing?
