### ISSUE TITLE
problem installation

### ISSUE THREAD

**Issue by Darkmagister** [madmicio/LG-WebOS-Remote-Control#36]
Hi,
i'm trying to install this component in my HA, 
i've installed manually browser mod (i could not find it in HACS), added **browser_mod:** in the configuration.yaml file
then i installed channel pad (from HACS frontend)
installed lg remote control (from HACS frontend)
restart HA (there were already url in lovelace resource)

create a new card in the home page 
```
- type: 'custom:lg-remote-control'
  entity: media_player.lg_salotto
```

but i still get this:
```
No card type found

- type: 'custom:lg-remote-control'
  entity: media_player.lg_salotto
```

any ideas??

thanks

**Comment by Darkmagister** [comment]
i'have made a stupid mistake, i've added the - before type in the gui... removing that solved the issue!!!

**Comment by madmicio** [comment]
👍

**Comment by pabsi** [comment]
I just got hit by this and I'd say it's a confusion with how the README is phrased.

I copied & pasted the code in the README, and that gives you this error. In my opinion the README should be amended?

Currently:
```
lovelace config: default view
- type: 'custom:lg-remote-control'
  entity: media_player.tv_lg_55c8```

What I think should be:
```
lovelace config: default view
type: 'custom:lg-remote-control'
entity: media_player.tv_lg_55c8```
