### ISSUE TITLE
Channel pad don't appear anymore

### ISSUE THREAD

**Issue by Scialla** [madmicio/LG-WebOS-Remote-Control#46]
with latest version of HA (2021.2.3 but is possibile release before too) Channel Pad with TV logo don't appear anymore

I use HA core in venv 201.2.3 on RPi 3b

Before this, all work fine

Alle other function works fine, only channel pad don't appear

Tried to reinstall card-channel-pad but nothing change
Tried with 5 different browser, cleared cache too, but nothing change

what can i check?

Thanks

**Comment by madmicio** [comment]
it's a problem with all custom cards. it is due to the latest browser_mod update.
for the moment the problem is temporarily resolved.
soon we will release an update with the final fix
