### ISSUE TITLE
Disney + button not working

### ISSUE THREAD

**Issue by tigroz** [madmicio/LG-WebOS-Remote-Control#5]
I can select Netflix and  Amazon Prime Video but not Disney +( I don’t have Dzne )

**Comment by madmicio** [comment]
we are working on a new version with customizable source buttons

**Comment by PiotrMachowski** [comment]
In current version you can customize displayed list of apps using `sources` parameter

**Comment by CosticaPuntaru** [comment]
this worked for me:
```
sources:
  - icon: disney
    name: Disney+
```
