### ISSUE TITLE
Changing sources stopped working

### ISSUE THREAD

**Issue by Dinth** [madmicio/LG-WebOS-Remote-Control#57]
Hi. I have had this lovelace card working perfectly fine for months, until recently. Now i cannot change the sources - i have tried multiple browsers and through iOS app. The sources are visible and the list updates, but clicking on any source doesnt do nothing. For the sake of troubleshooting, i have tried running media_player.select_source service and it works perfectly fine, so the issue is with the card. 
The problem started a few weeks ago, but i cannot exactly say when - if there was an update of Home Assistant or the card at that time.

**Comment by madmicio** [comment]
i just tested the card with HA core-2021.5.5 version.
It worked perfectly. as soon as possible I will update to the latest version and do further tests

**Comment by Dinth** [comment]
Hi. Im happy to provide you with a profile (generated through Dev Tools in Chrome) recording via email. But im not seeing any errors generated when clicking different sources. 
![Screenshot 2021-06-15 at 20 23 35](https://user-images.githubusercontent.com/313674/122111413-a273cd80-ce17-11eb-8b9c-e62d77a8de12.png)

**Comment by ned786** [comment]
@Dinth i have the same issue it worked perfectly but then stopped, i think it is to do with homeassistant 2021.06 update

**Comment by make-all** [comment]
The App buttons on the main control work for me, but the Source panel has stopped working.  It highlights the current source, but it is not possible to change source from there.  I deleted my yaml configration which was filtering it down to just the sources I use, in case something had changed in the underlying WebOS integration, but the problem remains.

**Comment by CeccoCQ** [comment]
Same issue here.

**Comment by CeccoCQ** [comment]
Found the bug.

Replace into js file:
```
  <button class="${stateObj.attributes.source === source ? 'btn-input-on' : 'btn-input  ripple overlay'}" @click=${() => {
                        this._select_source(source);
                        this._show_inputs = false;
                    }}}>${source}</button>

```

with:
`<button class="${stateObj.attributes.source === source ? 'btn-input-on' : 'btn-input  ripple overlay'}" @click=${() => this._select_source(source)}>${source}</button>`

Remove the integration from HACS, then add the new file to www folder and link manually the module from Settings > Lovelace dashboard > Resource as Javascript resource. 

Let me know if you have problems.

**Comment by PiotrMachowski** [comment]
@CeccoCQ thanks for your analysis, actual fix was even simpler. It should work now
