### ISSUE TITLE
Custom element not found

### ISSUE THREAD

**Issue by rw377** [madmicio/LG-WebOS-Remote-Control#60]
I have tried following the HACS install as well as manual installation but continue to get this error.  Running 2021.3.4.  I have also tried pointing to a /local/ directory in lovelace resources but continue to get this error.

![3](https://user-images.githubusercontent.com/75325891/123194134-fa43b180-d473-11eb-8ea4-d6c465b51b97.PNG)

**Comment by proffalken** [comment]
@rw377 did you solve this? I've just hit the same issue and would love to know how you fixed it!
