### ISSUE TITLE
Power off not working

### ISSUE THREAD

**Issue by zener05** [madmicio/LG-WebOS-Remote-Control#69]
Hi, when I try to turn off the TV, it does nothing - TV is still running.

All other buttons are working, there is a problem with power off button only. I have webOS gen 1 (47LB650V from 2014).

Can you help me, please? Thank you.

**Comment by madmicio** [comment]
Can you turn off the TV from the home assistant media player?

**Comment by zener05** [comment]
Yes, turning off from media player is working.

**Comment by zener05** [comment]
Any ideas, please?

Remote control is awesome, I use it every day but this turn off problem is little bit bad 😔

**Comment by baczus** [comment]
Hi,

first of all thanks for the great addon.

Could you provide ETA for the fix to this issue?

**Comment by truxntrax** [comment]
I have a tv with webos3 (60UH650V-ZB by LG Firmware: 05.60.25), but my power button has now stopped turning off my TV.  Same as OP, when I use the off button on the standard media card the TV turns off.  All the other buttons are still working.  I think this behaviour change happened as I updated to the latest Homeassistant version (2022.2.3).

**Comment by icornish72** [comment]
@truxntrax see breaking changes for the release.
Specific issue logged -https://github.com/madmicio/LG-WebOS-Remote-Control/issues/78

**Comment by truxntrax** [comment]
> @truxntrax see breaking changes for the release. Specific issue logged -#78

Hi, I have seen that issue. My issues is that power off doesn't work, like the op. I think issue 78 is around the power on  change.

**Comment by madmicio** [comment]
fixed
