### ISSUE TITLE
Power button not working after Feb 2022 HomeAssistant update

### ISSUE THREAD

**Issue by HuggyBearUK** [madmicio/LG-WebOS-Remote-Control#78]
Breaking changes has the following text for the latest release of HA.

> **LG webOS Smart TV**
> The LG webOS Smart TV integration migrated to configuration via the UI. Configuring LG webOS Smart TV via YAML configuration has been deprecated and will be removed in a future Home Assistant release.
> 
> Your existing YAML configuration is automatically imported on upgrade to this release; and thus can be safely removed from your YAML configuration after upgrading.
> 
> The [turn on action](https://www.home-assistant.io/integrations/webostv/#turn-on-action) for turning on the TV via WakeOnLan or HDMI-CEC was using a service call via YAML, and the turn on action is changed to use a custom automation trigger webostv.turn_on or a device trigger automation that can be setup from the UI.

https://www.home-assistant.io/integrations/webostv/

> You can create an automation from the user interface, from the device create a new automation and select the Device is requested to turn on automation. Automations can also be created using an automation action:

This resolves the issue and the 'Power' button works once more.

**Comment by tempmaseg** [comment]
@HuggyBearUK did you create an automation so it still works or is just for the developer to know how to fix it?

**Comment by HuggyBearUK** [comment]
Hi,

I created an automation using the Home Assistant GUI 
The trigger has the platform **device** and type '**_Device_ is requested to turn on**'.
The action calls the **service** _**wake_on_lan.send_magic_packet**_ with the MAC address of the TV.

My configuration.yaml file no longer contains any configuration for the **webostv** integration but **_wake_on_lan:_** still must be present in the config.

![image](https://user-images.githubusercontent.com/79339083/153579531-9a48146a-b81c-45c4-8344-c8ba57a93823.png)

![image](https://user-images.githubusercontent.com/79339083/153579673-def947a6-81d4-40d5-a9d1-99f5d90e5858.png)
![image](https://user-images.githubusercontent.com/79339083/153579737-ef9e4fa3-d885-47e3-b29e-7ad97fa8d9a7.png)


![image](https://user-images.githubusercontent.com/79339083/153580054-33aaccc3-ee1d-4328-920c-d6356b604c14.png)

**Comment by HuggyBearUK** [comment]
I do not think the developer needs to do anything.  My post was to share my experience.

**Comment by tempmaseg** [comment]
Great, thank you! 👍

**Comment by raffpapalia** [comment]
@HuggyBearUK thanks for this, i'll give it a try. This will work to turn the TV on, how about turning it off?

**Comment by madmicio** [comment]
fixed
