### ISSUE TITLE
new release  problem on ios companion app

### ISSUE THREAD

**Issue by tigroz** [madmicio/LG-WebOS-Remote-Control#9]
the new version does not appear on the ios app,
on the version on the pc everything ok, instead on the ios app says:

```
Custom element doesn't exist: lg-remote-control.
entity: media_player.tv_lg  
type: 'custom: lg-remote-control'
```

**Comment by jscherry** [comment]
I’m getting the same error on Mac safari

**Comment by PiotrMachowski** [comment]
@jscherry Could you please attach any errors from browsers console?

**Comment by tigroz** [comment]
yep..tested me too Safari on MacBook and  i'm getting the same error

**Comment by PiotrMachowski** [comment]
@tigroz Could you please attach any errors from browsers console?

**Comment by madmicio** [comment]
I don't know if this is the case. but as early as yesterday, hacs seemed crazy. many users complained about the same problem on many well-tested cards like browser_mod_ custom_state_switch etc etc.

if you can, compare the github code with the one on your device.
try to understand if it is the same.

**Comment by tigroz** [comment]
> @tigroz Could you please attach any errors from browsers console?

can you please show me how to do?

**Comment by tigroz** [comment]
> I don't know if this is the case. but as early as yesterday, hacs seemed crazy. many users complained about the same problem on many well-tested cards like browser_mod_ custom_state_switch etc etc.
> 
> if you can, compare the github code with the one on your device.
> try to understand if it is the same.

you mean compare browse_mod ? or LG WebOS Remote Control?

**Comment by madmicio** [comment]
compare the code on github and that of your card. this is done for all three cards of the remote control. if they are the same, delete the gz file in the directories of the three cards, clear the cache and see if it works. as I was telling you in the past few days this problem I also encountered with the updating of other cards

**Comment by tigroz** [comment]
i've deleted all 3 plugin, rebooted reinstalled and the error persists

**Comment by PiotrMachowski** [comment]
@jscherry @tigroz Could you please attach any errors from browsers console?

**Comment by tigroz** [comment]
<img width="1260" alt="Schermata 2020-04-25 alle 16 35 05" src="https://user-images.githubusercontent.com/1850818/80282636-d4f1d100-8712-11ea-937c-3d9a686b18d7.png">
 this screenshot could be ok?

**Comment by PiotrMachowski** [comment]
It's almost enough, there's some missing text on the right side.
From what I can see it seems like an issue with hacs serving the file

**Comment by ykiv63** [comment]
> i've deleted all 3 plugin, rebooted reinstalled and the error persists

For me also. Don't works. Same error.

**Comment by tigroz** [comment]
i've done new screenshot now you can read all the text, any advice?
thanks :)
<img width="1434" alt="Schermata 2020-04-27 alle 15 11 41" src="https://user-images.githubusercontent.com/1850818/80376218-c8e44b80-8899-11ea-9702-84b0a0e7fc14.png">

**Comment by jscherry** [comment]
![Image 4-27-20 at 3 53 PM](https://user-images.githubusercontent.com/13368828/80419936-989fab80-889f-11ea-9d28-d0669a1420c4.jpg)

**Comment by jscherry** [comment]
Above is a screenshot from an iMac. I tried deleting the gz file associated with each card as recommended and cleared the browser cache. Still not working on safari for Mac, safari on iOS, but works fine using Chrome. Has to have something to do with the Safari browser?

**Comment by PiotrMachowski** [comment]
@tigroz @jscherry thanks, I know the source of a problem now. The card used feature that is not supported by Safari. I should be able to fix it shortly

**Comment by jscherry** [comment]
How do you set the channels for the channel pad card?

**Comment by jscherry** [comment]
Nevermind I found the info to set channels, sorry.

**Comment by madmicio** [comment]
![Schermata 2020-04-28 alle 00 49 45](https://user-images.githubusercontent.com/42836292/80428466-37e99080-88ea-11ea-91c9-69e6caf23e46.png)

**Comment by jscherry** [comment]
Just tried it using Chrome and Firefox on iOS devices. Neither work but It works fine on my iMac with Chrome? Is there something preventing the plugin from working on Apple mobile devices. Also no luck with the iOS home assistant companion app.

**Comment by jscherry** [comment]
We’re you guys able to correct the code issue prohibiting it from working with Safari and Apple mobile devices?

**Comment by PiotrMachowski** [comment]
We have a working version on a dev branch, it should be available today.

**Comment by PiotrMachowski** [comment]
It should be fixed in current version, could you confirm it?

**Comment by tigroz** [comment]
now the custom card is loaded, the problem is the backgroud color of the buttons
![Immagine](https://user-images.githubusercontent.com/1850818/80647493-d7379080-8a6e-11ea-924d-05ecf7edc2f7.png)

**Comment by PiotrMachowski** [comment]
Colors are now configurable in a configuration: [documentation](https://github.com/madmicio/LG-WebOS-Remote-Control#color-management)

**Comment by nandin0** [comment]
not work, same error in raspberrypi 3

Custom element doesn't exist: lg-remote-control.
entity: media_player.tv_lg  
type: 'custom: lg-remote-control'

**Comment by rvsoftz** [comment]
I was getting this error with my Raspberry setup.
The strange solution was to rename the folder from “LG-WebOS-Remote-Control” to something lowercase like “lg-remote-control”.
After updating the resource url and a full restart, the remote suddenly appears on my dashboard.
